### ISSUE TITLE
Allow distributed execution by allowing planner, executor to be swapped out

### ISSUE THREAD

**Issue by araddon** [araddon/qlbridge#65]
Allow a distributed planner (dataux) to replace built in qlbridge execution planner (in `exec` ) .   Currently there is no separation of planning, execution, and no strong interface to allow the distributed executor to replace the native in-process qlbridge executor. Also, no serialization interfaces/capability to allow tasks to be deterministically distributed, and no primitives (partitions, tablets) to allow work to be broken down. 

**Phase 1 usecase**:   Query Mongo with 3 nodes participating, a groub-by aggregate query `select AVG(CHAR_LENGTH(CAST(`title` AS CHAR))) as title_avg from article GROUP BY category`

* [x] **1** refactor the exec job builders to support over-riding core behavior
  * [x] `plan.Visitor` with full suite of plan structs instead of using `rel` sql structs
  * [x] revamp the task assembly (list of tasks, `taskparent.Add(task)`) to be interfaces not implementation
  * [x] allow the job builder to have a `TaskMaker` factory for overriding built in task implementations
  * [x] split the core visitor interfaces in exec into plan.Planner, exec.Walk where the output is dag of plan.Task
    * [x] `plan.PlannerDefault` and all new plan types
    * [x] implement new Walk Executor in exec that translates the plans -> tasks
  * [x] move all of the plan, and exec Task creation into NewTaskName methods
* [x] **4** Partitionalble sources:   underlying sources/interfaces need to be able to support some type of partitioning so a source query can be split across nodes.
     * [x] hack in quick partition storage (`Custom`)
     * [x] fix the distributed/group-by to pass underlying values (tuple?) allowing calculating finalization.
* [x] **5** network/serialization distributed-enable
   * [x] protobuf plan.Tasks
  * [x] protobuf implementation for node
  * [x] protobuf for sql (only select ops) structs

depended on by https://github.com/dataux/dataux/issues/9

moving until later:

* **6** allow visualization of dag of tasks by supporting `MarshalJson()`  or `Explain()`?
